services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: sqlserver-act-hotelaria
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=ACT-Hotelaria2026@
    ports:
      - "1433:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql
    networks:
      - act-hotelaria-network
    healthcheck:
      test: ["CMD", "/opt/mssql-tools18/bin/sqlcmd", "-S", "localhost", "-U", "sa", "-P", "ACT-Hotelaria2026@", "-Q", "SELECT 1", "-C"]
      interval: 10s
      timeout: 4s
      retries: 10
      start_period: 10s
      
  redis:
    image: redis:7.0-alpine
    container_name: redis-act-hotelaria
    ports:
      - "6379:6379"
    networks:
      - act-hotelaria-network
    restart: unless-stopped

  ACT-Hotelaria:
    build:
      context: .
      dockerfile: ACT-Hotelaria/Dockerfile
    image: act-hotelaria-api
    container_name: act-hotelaria
    depends_on:
      sqlserver:
        condition: service_healthy
    ports:
      - "8080:8080"
      - "8081:8081"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=sqlserver;Database=hotelaria;User Id=sa;Password=ACT-Hotelaria2026@;TrustServerCertificate=True;
    networks:
      - act-hotelaria-network
    restart: unless-stopped

volumes:
  sqlserver_data:

networks:
  act-hotelaria-network:
    driver: bridge